language: node_js

env:
  - CXX=g++-4.8

node_js:
  - 6
  - 8
  - 9
  - 10

sudo: required

notifications:
  email:
    - lilleman@larvit.se
    - tobias@nublar.se

before_install:
  - $CXX --version

before_script:
  - mysql -e 'CREATE DATABASE test'

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - npm i

services:
  - rabbitmq
  - mysql

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script: DBCONFFILE=../config/db_travis.json INTCONFFILE=../config/amqp_travis.json mocha
